name: Tests

on:
  [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        php: [8.4, 8.3]
        laravel: [13.*, 12.*]
        stability: [prefer-stable]
        firebird: [v2.5.9-sc]
        include:
          - laravel: 12.*
            testbench: ^10.3
          - laravel: 13.*
            testbench: ^11.0
      fail-fast: false

    name: PHP ${{ matrix.php }}, Laravel ${{ matrix.laravel }}, Firebird ${{ matrix.firebird }}, ${{ matrix.stability }}

    services:
      firebird:
        image: jacobalberty/firebird:${{ matrix.firebird }}
        env:
          FIREBIRD_DATABASE: 'database.fdb'
          ISC_PASSWORD: 'masterkey'
          EnableLegacyClientAuth: 'true'
        ports:
          - 3050:3050

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: pdo_firebird
          tools: composer:v2
          coverage: none

      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
          composer update --${{ matrix.stability }} --prefer-dist --no-interaction

      - name: Execute tests
        run: vendor/bin/phpunit
